### ISSUE TITLE
Deed types: Confirm with Res Val and Publish

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/model-sales-val#136]
## Goal:
We are frequently asked what deed types are included or excluded for training the model. While we also have our sales val heuristics, I'd like to create an easy-to-reference table of deed types in our wiki or res repo readme, and to validate it with Res Val.

## Example:
Below is what I've sort of pulled together from various blobs of code and googling. I don't guarantee it's correct! 

| Deed type | Deed type description | Included or excluded? | Info | 
| ------------ | ----------------------| ---------------| ----------------------------------- |
| 01 | Warranty Deed | Included | Most common; guarantees ownership | 
| 02 | Trustee Deed | Included | Transmits property into a trust; can be quit claim or warranty. | 
| 03 | Quit Claim Deed | Excluded | Renounces interest; does not promise property is free of third-party interests, like liens. | 
| 04 | Executor Deed | Excluded | Transfers property out of an estate. | 
| 05 | Other | Included | ? | 
| 06 | Beneficial Interest | Excluded | ? | 
| (null) | (null) | Excluded |  |
|   | Special Warranty | ? | Typically used for foreclosure purchase | 
| 99 | Unknown | ? |  |

## Tasks:

- [ ] Go through our docs and code and correct the above. Helpful terms are "deed" and "exclude". 
- [ ] When confirmed, reach out to @ccao-jardine; she'll schedule a meeting with you, Data leadership, and Res Val to confirm current choices and ask if they have suggestions. This could maybe be tacked on to [model-sales-val #77](https://github.com/ccao-data/model-sales-val/issues/77.)
- [ ] With an updated table, please create a PR to add a section to to the [glossary](https://github.com/ccao-data/wiki/blob/master/Handbook/Glossary.md).

**Comment by Damonamajor** [comment]
@ccao-jardine 
[Deed Types.xlsx](https://github.com/user-attachments/files/18171005/Deed.Types.xlsx)
